# Use Debian buster as OS environment
FROM python:3.7-buster

# Copy over stuff
COPY requirements.txt /requirements.txt
COPY tests /tests

# Install dependencies
RUN pip3 install -r requirements.txt

# RUNIT
ENTRYPOINT ["/tests/start_test.sh"]
