version: '3'

services:
  app:
    image: ttm
    build:
      context: .
    depends_on:
      - mongo
      - mongo-express
    environment:
      MONGO_URL: "mongodb://twmadmin:twm999@mongo:27017"
      ADMIN_PASS: "ttmadmin"
      JWT_SECRET: "ttmadmin"
    ports:
      - 8000:8000

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: twmadmin
      MONGO_INITDB_ROOT_PASSWORD: twm999
    ports:
      - 58017:27017
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 58081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: twmadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: twm999

volumes:
  mongo:
