name: test
on: [push]
jobs:
  lint_check: 
    runs-on: ubuntu-latest
    steps:
      - name: copy stuff into the repo
        uses: actions/checkout@v1
      - name: install linter
        run: sudo apt-get install -y pycodestyle
      - name: vibe check
        run: pycodestyle app.py
  main_test:
    runs-on: ubuntu-latest
    steps:
      - name: setup python3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: fix pip
        run: sudo apt-get install pip3 -y
      - name: copy stuff from repo to worker directory
        uses: actions/checkout@v1
      - run: pip3 install pytest requests socketio
      - name: compose the docker stack
        run: docker-compose up --build -d
      - name: run tests
        run: python -m pytest tests

