name: actions_test
on: [push]
jobs:
  test_python_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get install python3.7
      - run: python3.7 -V
