name: test
on: [push]
jobs:
  main_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get install -y python3.7 python3-pip
      - run: pip3 install flask flask-pymongo flask-cors flask-socketio apscheduler
      - run: python3.7 app.py
