name: test
on: [push]
jobs:
  main_test:
    runs-on: ubuntu-latest
    steps:
      - name: copy stuff from repo to worker directory
        uses: actions/checkout@v1
      - name: start the docker container
        uses: ./
        id: talk-to-me backend
