name: test
on: [push]
jobs:
  lint_check: 
    runs-on: ubuntu-latest
    steps:
      - name: copy stuff into the repo
        uses: actions/checkout@v1
      - name: install linter
        uses: apt-get install pycodestyle
      - name: vibe check
        uses: pycodestyle app.py
  main_test:
    runs-on: ubuntu-latest
    steps:
      - name: copy stuff from repo to worker directory
        uses: actions/checkout@v1
      - name: start the docker container
        uses: ./
