name: test
on: [push]
jobs:
  lint_check: 
    runs-on: ubuntu-latest
    steps:
      - name: copy stuff into the repo
        uses: actions/checkout@v1
      - name: install linter
        run: sudo apt-get install -y pycodestyle
      - name: vibe check
        run: pycodestyle app.py
  main_test:
    runs-on: ubuntu-latest
    steps:
      - name: copy stuff from repo to worker directory
        uses: actions/checkout@v1
<<<<<<< HEAD
      - run: pip3 install pytest requests socketio
=======
      - run: pip install pytest requests
>>>>>>> parent of 6addbd7... update test dependencies in github workflow
      - name: compose the docker stack
        run: docker-compose up --build -d
      - name: run tests
        run: python3.7 -m pytest tests

